name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag info909:latest
      
    - name: Push to GitHub Packages
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: visarsylejmani/info909:latest

